import React, { useMemo, useState, useCallback, useEffect } from 'react';
import { createPortal } from 'react-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { apiRequest } from '../../../lib/api';
import { broadcastInvalidation } from '../../../lib/crossTabInvalidate';
import { LoadingSpinner } from '../../../shared/components/LoadingSpinner';
import { ErrorState } from '../../../shared/components/ErrorState';
import { EmptyState } from '../../../shared/components/EmptyState';
import { usePageAnimations } from '../../../shared/hooks/usePageAnimations';
import { showToast, showToastInteractive } from '../../../shared/utils/toastUtils';
import { SearchInput } from '../../../shared/components/SearchInput';
import { getPrintLogoAndFooter, openPrintWindow, downloadTableAsExcel, generateKampanyaPrintHTML } from '../../dashboard/utils/exportUtils';
import { getUploadUrl } from '../../../shared/utils/urlUtils';
import { getApiBaseUrl } from '../../../lib/runtime';
import { Pencil, Trash2 } from 'lucide-react';
import { TableSortHeader } from '../../../shared/components/TableSortHeader';
import { Lightbox } from '../../../shared/components/Lightbox';

interface Campaign {
  id: number;
  ad: string;
  mesaj?: string;
  musteri_grubu?: string;
  baslangic_tarihi: string;
  bitis_tarihi: string;
  kupon_kodu?: string;
  gorsel_path?: string;
  gorsel?: string;
  durum?: string;
  gonderildi?: number | boolean;
  toplam_gonderilen?: number;
  basarili_gonderilen?: number;
  basarisiz_gonderilen?: number;
}

const defaultFormData = {
  ad: '',
  musteri_grubu: 'tum-musteriler',
  kupon_kodu: '',
  baslangic_tarihi: '',
  bitis_tarihi: '',
  mesaj: '',
  gorsel: null as File | null,
  gorsel_path: null as string | null,
};

function generateKampanyaMessage(
  kampanyaAdi: string,
  baslangicTarihi: string,
  bitisTarihi: string,
  kuponKodu: string
): string {
  const formatDate = (dateStr: string) => {
    if (!dateStr) return '';
    const d = new Date(dateStr);
    const gun = d.getDate();
    const ay = d.toLocaleDateString('tr-TR', { month: 'long' });
    const yil = d.getFullYear();
    return `${gun} ${ay} ${yil}`;
  };
  const formattedBaslangic = formatDate(baslangicTarihi);
  const formattedBitis = formatDate(bitisTarihi);
  const adLower = kampanyaAdi.toLowerCase();
  let baseMessage = '';
  if (adLower.includes('sevgililer')) {
    baseMessage = `${kampanyaAdi} kapsamında tüm buket siparişlerinizde özel indirim sizi bekliyor.`;
  } else if (adLower.includes('anneler')) {
    baseMessage = `${kampanyaAdi} kapsamında tüm çiçek siparişlerinizde özel indirim fırsatı!`;
  } else if (adLower.includes('düğün')) {
    baseMessage = `${kampanyaAdi} ile düğün çiçeklerinizde muhteşem indirimler!`;
  } else if (adLower.includes('doğum')) {
    baseMessage = `${kampanyaAdi} ile yeni doğan bebekler için özel çiçek aranjmanları!`;
  } else {
    baseMessage = `${kampanyaAdi} kapsamında özel indirim fırsatı sizi bekliyor.`;
  }
  return `${baseMessage} Kampanya ${formattedBaslangic} ile ${formattedBitis} tarihleri arasında geçerlidir. *Kupon Kodu: ${kuponKodu}*`;
}

function isAutoGeneratedMessage(msg: string): boolean {
  return (
    msg.includes('Kampanya') &&
    msg.includes('tarihleri arasında geçerlidir') &&
    msg.includes('Kupon Kodu:')
  );
}

function getMusteriGrubuText(grup: string): string {
  return grup === 'tum-musteriler' ? 'Tüm Müşteriler' : grup || 'Belirtilmemiş';
}

function getStatusText(durum: string): string {
  const map: Record<string, string> = {
    taslak: 'TASLAK',
    'devam-ediyor': 'DEVAM EDİYOR',
    tamamlandi: 'TAMAMLANDI',
  };
  return map[durum] || (durum || '').toUpperCase();
}

const MOBILE_BREAKPOINT = 767;

function useIsMobile(): boolean {
  const [isMobile, setIsMobile] = useState(() =>
    typeof window !== 'undefined' ? window.matchMedia(`(max-width: ${MOBILE_BREAKPOINT}px)`).matches : false
  );
  useEffect(() => {
    const mq = window.matchMedia(`(max-width: ${MOBILE_BREAKPOINT}px)`);
    const handler = () => setIsMobile(mq.matches);
    mq.addEventListener('change', handler);
    return () => mq.removeEventListener('change', handler);
  }, []);
  return isMobile;
}

export const CampaignsPage: React.FC = () => {
  usePageAnimations('campaigns');
  const isMobile = useIsMobile();
  const queryClient = useQueryClient();
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCampaignId, setSelectedCampaignId] = useState<number | null>(null);
  const [showNewForm, setShowNewForm] = useState(false);
  const [exportMenuOpen, setExportMenuOpen] = useState(false);
  const [sortField, setSortField] = useState<string | null>(null);
  const [sortDir, setSortDir] = useState<'asc' | 'desc'>('asc');
  const [formData, setFormData] = useState(defaultFormData);
  const [uploadingImage, setUploadingImage] = useState(false);
  const [campaignImageLightboxOpen, setCampaignImageLightboxOpen] = useState(false);

  const { data: campaigns, isLoading, error } = useQuery({
    queryKey: ['campaigns'],
    queryFn: async () => {
      try {
        const result = await apiRequest<Campaign[]>('/kampanyalar', { method: 'GET' });
        return Array.isArray(result) ? result : [];
      } catch (err) {
        if (err instanceof Error && 'status' in err && (err as { status?: number }).status === 404) {
          return [];
        }
        console.error('Kampanyalar yükleme hatası:', err);
        return [];
      }
    },
    staleTime: 2 * 60 * 1000,
    retry: false,
  });

  const { data: customers } = useQuery({
    queryKey: ['customers'],
    queryFn: async () => {
      try {
        const result = await apiRequest<{ musteri_grubu?: string }[]>('/customers', { method: 'GET' });
        return Array.isArray(result) ? result : [];
      } catch {
        return [];
      }
    },
    staleTime: 5 * 60 * 1000,
  });

  const musteriGruplari = useMemo(() => {
    const gruplar = new Set<string>(['tum-musteriler', 'VIP', 'Kurumsal', 'Bireysel', 'Standart']);
    customers?.forEach((c) => {
      if (c.musteri_grubu?.trim()) gruplar.add(c.musteri_grubu.trim());
    });
    return Array.from(gruplar).sort();
  }, [customers]);

  const filteredCampaigns = useMemo(() => {
    if (!campaigns?.length) return [];
    const q = searchQuery.trim().toLowerCase();
    if (!q) return campaigns;
    return campaigns.filter(
      (c) =>
        (c.ad ?? '').toLowerCase().includes(q) ||
        (c.kupon_kodu ?? '').toLowerCase().includes(q) ||
        (c.musteri_grubu ?? '').toLowerCase().includes(q)
    );
  }, [campaigns, searchQuery]);

  const sortedCampaigns = useMemo(() => {
    const data = [...filteredCampaigns];
    if (!sortField) return data;
    return data.sort((a, b) => {
      let cmp = 0;
      switch (sortField) {
        case 'ad': cmp = (a.ad ?? '').localeCompare(b.ad ?? ''); break;
        case 'grubu': cmp = (a.musteri_grubu ?? '').localeCompare(b.musteri_grubu ?? ''); break;
        case 'kupon': cmp = (a.kupon_kodu ?? '').localeCompare(b.kupon_kodu ?? ''); break;
        case 'baslangic': cmp = (a.baslangic_tarihi ?? '').localeCompare(b.baslangic_tarihi ?? ''); break;
        case 'bitis': cmp = (a.bitis_tarihi ?? '').localeCompare(b.bitis_tarihi ?? ''); break;
        case 'durum': cmp = (a.durum ?? '').localeCompare(b.durum ?? ''); break;
        default: return 0;
      }
      return sortDir === 'asc' ? cmp : -cmp;
    });
  }, [filteredCampaigns, sortField, sortDir]);

  const handleSort = (field: string, dir: 'asc' | 'desc') => {
    setSortField(field);
    setSortDir(dir);
  };

  const selectedCampaign = useMemo(
    () => campaigns?.find((c) => c.id === selectedCampaignId) ?? null,
    [campaigns, selectedCampaignId]
  );

  // Taslak kampanya satıra tıklandığında formu kampanya verisiyle doldur (görsel dahil)
  useEffect(() => {
    if (selectedCampaign && !selectedCampaign.gonderildi && !showNewForm) {
      setFormData({
        ad: selectedCampaign.ad || '',
        musteri_grubu: selectedCampaign.musteri_grubu || 'tum-musteriler',
        kupon_kodu: selectedCampaign.kupon_kodu || '',
        baslangic_tarihi: selectedCampaign.baslangic_tarihi || '',
        bitis_tarihi: selectedCampaign.bitis_tarihi || '',
        mesaj: selectedCampaign.mesaj || '',
        gorsel: null,
        gorsel_path: selectedCampaign.gorsel_path || selectedCampaign.gorsel || null,
      });
    }
  }, [selectedCampaign, showNewForm]);

  const handleAutoMessage = useCallback(() => {
    setFormData((p) => {
      if (p.ad && p.baslangic_tarihi && p.bitis_tarihi && p.kupon_kodu) {
        const autoMsg = generateKampanyaMessage(
          p.ad,
          p.baslangic_tarihi,
          p.bitis_tarihi,
          p.kupon_kodu
        );
        if (!p.mesaj || isAutoGeneratedMessage(p.mesaj)) {
          return { ...p, mesaj: autoMsg };
        }
      }
      return p;
    });
  }, []);

  const handleImageUpload = async (file: File) => {
    if (!file.type.startsWith('image/')) {
      showToast('error', 'Lütfen sadece görsel dosyası seçin.');
      return;
    }
    if (file.size > 5 * 1024 * 1024) {
      showToast('error', 'Dosya boyutu 5MB\'dan küçük olmalıdır.');
      return;
    }
    setUploadingImage(true);
    try {
      const fd = new FormData();
      fd.append('file', file);
      const token = localStorage.getItem('floovon_token') || localStorage.getItem('token');
      const baseUrl = getApiBaseUrl();
      const res = await fetch(`${baseUrl}/kampanyalar/upload`, {
        method: 'POST',
        body: fd,
        credentials: 'include',
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      });
      const json = await res.json().catch(() => null);
      if (!res.ok || !json?.success) {
        throw new Error(json?.error || json?.message || 'Görsel yüklenemedi');
      }
      const path = json?.data?.path ?? json?.path ?? '';
      setFormData((p) => ({ ...p, gorsel: file, gorsel_path: path || null }));
      showToast('success', 'Görsel yüklendi');
    } catch (err: unknown) {
      showToast('error', (err as Error)?.message || 'Görsel yüklenemedi');
    } finally {
      setUploadingImage(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    let mesaj = formData.mesaj.trim();
    if (
      !mesaj ||
      isAutoGeneratedMessage(mesaj)
    ) {
      mesaj = generateKampanyaMessage(
        formData.ad,
        formData.baslangic_tarihi,
        formData.bitis_tarihi,
        formData.kupon_kodu
      );
    }
    const payload = {
      ad: formData.ad,
      mesaj,
      musteri_grubu: formData.musteri_grubu || 'tum-musteriler',
      baslangic_tarihi: formData.baslangic_tarihi,
      bitis_tarihi: formData.bitis_tarihi,
      kupon_kodu: formData.kupon_kodu || null,
      gorsel_path: formData.gorsel_path || null,
    };
    try {
      if (selectedCampaign && !selectedCampaign.gonderildi) {
        await apiRequest(`/kampanyalar/${selectedCampaign.id}`, {
          method: 'PUT',
          data: payload,
        });
        showToast('success', 'Kampanya güncellendi');
      } else {
        await apiRequest('/kampanyalar', {
          method: 'POST',
          data: payload,
        });
        showToast('success', 'Kampanya oluşturuldu');
      }
      queryClient.invalidateQueries({ queryKey: ['campaigns'] });
      broadcastInvalidation([['campaigns']]);
      setFormData(defaultFormData);
      setShowNewForm(false);
      setSelectedCampaignId(null);
    } catch (err: unknown) {
      showToast('error', (err as Error)?.message || 'İşlem başarısız');
    }
  };

  const handleDelete = (campaign: Campaign) => {
    if (campaign.gonderildi) {
      showToast('warning', 'Gönderilmiş kampanyalar silinemez');
      return;
    }
    showToastInteractive({
      title: 'Kampanya Sil',
      message: `"${campaign.ad}" kampanyasını silmek istediğinize emin misiniz?`,
      confirmText: 'Evet, Sil',
      cancelText: 'İptal',
      onConfirm: async () => {
        try {
          await apiRequest(`/kampanyalar/${campaign.id}`, { method: 'DELETE' });
          showToast('success', 'Kampanya silindi');
          queryClient.invalidateQueries({ queryKey: ['campaigns'] });
          broadcastInvalidation([['campaigns']]);
          if (selectedCampaignId === campaign.id) {
            setSelectedCampaignId(null);
            setShowNewForm(false);
            setFormData(defaultFormData);
          }
        } catch (err: unknown) {
          showToast('error', (err as Error)?.message || 'Silinemedi');
        }
      },
    });
  };

  const handleEdit = (campaign: Campaign) => {
    if (campaign.gonderildi) {
      showToast('warning', 'Gönderilmiş kampanyalar düzenlenemez');
      return;
    }
    setSelectedCampaignId(campaign.id);
    setShowNewForm(true);
    setFormData({
      ad: campaign.ad || '',
      musteri_grubu: campaign.musteri_grubu || 'tum-musteriler',
      kupon_kodu: campaign.kupon_kodu || '',
      baslangic_tarihi: campaign.baslangic_tarihi || '',
      bitis_tarihi: campaign.bitis_tarihi || '',
      mesaj: campaign.mesaj || '',
      gorsel: null,
      gorsel_path: campaign.gorsel_path || campaign.gorsel || null,
    });
  };

  const handleNewClick = () => {
    setSelectedCampaignId(null);
    setFormData(defaultFormData);
    setShowNewForm(true);
  };

  const handleExport = async (type: 'excel' | 'print') => {
    if (type === 'excel') {
      const exportData = (filteredCampaigns || []).map((c) => ({
        'Kampanya Adı': c.ad,
        'Müşteri Grubu': getMusteriGrubuText(c.musteri_grubu || ''),
        'Kupon Kodu': c.kupon_kodu || '',
        'Başlangıç': c.baslangic_tarihi,
        'Bitiş': c.bitis_tarihi,
        'Durum': getStatusText(c.durum || ''),
      }));
      if (!exportData.length) {
        showToast('warning', 'Dışa aktarılacak veri yok');
        return;
      }
      try {
        downloadTableAsExcel(exportData, 'Kampanyalar');
        showToast('success', 'Excel indirildi');
      } catch (e) {
        showToast('error', 'Excel dışa aktarılamadı');
      }
    } else {
      const { logoMarkup, footerHtml } = await getPrintLogoAndFooter();
      const html = generateKampanyaPrintHTML(
        filteredCampaigns || [],
        logoMarkup,
        footerHtml,
        getUploadUrl,
        getMusteriGrubuText,
        getStatusText
      );
      openPrintWindow(html, 'Kampanya Listesi');
    }
    setExportMenuOpen(false);
  };

  const showForm = showNewForm;
  const formTitle = selectedCampaignId ? 'Kampanya Düzenle' : 'Yeni Kampanya Oluştur';
  const submitLabel = selectedCampaignId ? 'KAMPANYAYI GÜNCELLE' : 'KAMPANYA OLUŞTUR';

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <LoadingSpinner size="lg" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gray-50">
        <ErrorState
          title="Kampanyalar yüklenemedi"
          message={error instanceof Error ? error.message : 'Bilinmeyen hata'}
        />
      </div>
    );
  }

  return (
    <div
      className="page-wrapper min-h-screen flex flex-col md:flex-row"
      onClick={() => !showForm && setSelectedCampaignId(null)}
    >
      {/* Sol panel - Tablo */}
      <div className="page-panel-sol w-full md:w-1/2 lg:w-2/5" onClick={(e) => e.stopPropagation()}>
        <div className="p-4 md:p-6">
          <div className="mb-6 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
            <div>
            <h1 className="page-title">
              Kampanya Listesi
              {filteredCampaigns.length > 0 && (
                <span className="page-title-badge">{filteredCampaigns.length}</span>
              )}
            </h1>
            </div>
            <div className="flex items-center gap-2">
              <button type="button" onClick={handleNewClick} className="page-btn-yeni">
                + Yeni Kampanya Oluştur
              </button>
              <div className={`buton-disa-aktar clickdropdown page-export-dropdown ${exportMenuOpen ? 'is-open' : ''}`}>
                <div className="btn-baslik">
                  <i className="icon-dashboard-disa-aktar" />
                  Dışa Aktar
                </div>
                <div className="dosya-tur clickdropbtn" onClick={() => setExportMenuOpen(!exportMenuOpen)}>
                  .xls
                  <i className="fa-solid fa-chevron-down" />
                </div>
                {exportMenuOpen && (
                  <div className="dosya-tur-content clickdropdown-content">
                    <div className="liste-baslik">Kampanyaları Dışa Aktar</div>
                    <button type="button" className="btn-disa-aktar" onClick={() => handleExport('excel')}>
                      <i className="icon-disa-aktar-excel" />
                      Excel'e Aktar
                    </button>
                    <button type="button" className="btn-yazdir" onClick={() => void handleExport('print')}>
                      <i className="icon-disa-aktar-yazdir" />
                      Yazdır
                    </button>
                  </div>
                )}
              </div>
            </div>
          </div>

          <div className="mb-6">
            <SearchInput
              value={searchQuery}
              onChange={setSearchQuery}
              placeholder="Kampanyalar içerisinde arayın"
              className="page-search-input"
              aria-label="Kampanya ara"
            />
          </div>

          {!filteredCampaigns.length ? (
            <EmptyState
              title={campaigns?.length ? 'Arama sonucu bulunamadı' : 'Görüntülenecek kampanya bulunamadı'}
              description={campaigns?.length ? 'Farklı bir arama terimi deneyin.' : 'Henüz kampanya kaydı bulunmamaktadır.'}
            />
          ) : (
            <div className="page-table-wrapper campaigns-table-wrapper campaigns-table-wrap">
              <div className="page-table-scroll campaigns-table-scroll table-scrollbar">
                <table className="w-full page-table campaigns-table" id="kampanyalar-tablo-export">
                  <thead>
                    <tr>
                      <th className="campaigns-th-gorsel">Görsel</th>
                      <TableSortHeader field="ad" label="Kampanya Adı" currentSort={sortField} sortDirection={sortDir} onSort={handleSort} />
                      <TableSortHeader field="grubu" label="Müşteri Grubu" currentSort={sortField} sortDirection={sortDir} onSort={handleSort} className="customers-th-grubu" />
                      <TableSortHeader field="kupon" label="Kupon Kodu" currentSort={sortField} sortDirection={sortDir} onSort={handleSort} />
                      <TableSortHeader field="baslangic" label="Başlangıç" currentSort={sortField} sortDirection={sortDir} onSort={handleSort} />
                      <TableSortHeader field="bitis" label="Bitiş" currentSort={sortField} sortDirection={sortDir} onSort={handleSort} />
                      <TableSortHeader field="durum" label="Durum" currentSort={sortField} sortDirection={sortDir} onSort={handleSort} />
                      <th className="campaigns-th-islemler">İşlemler</th>
                    </tr>
                  </thead>
                  <tbody>
                    {sortedCampaigns.map((c) => (
                      <tr
                        key={c.id}
                        className={`page-table-row campaigns-table-row ${selectedCampaignId === c.id ? 'page-table-row-selected campaigns-table-row-selected' : ''}`}
                        onClick={() => setSelectedCampaignId(c.id)}
                        data-table-row
                      >
                        <td className="campaigns-td-gorsel" data-label="Görsel">
                          {c.gorsel_path || c.gorsel ? (
                            <img
                              src={getUploadUrl(c.gorsel_path || c.gorsel || '')}
                              alt=""
                              className="campaigns-table-gorsel"
                            />
                          ) : (
                            <span className="campaigns-gorsel-placeholder">—</span>
                          )}
                        </td>
                        <td className="customers-td-code td-no-mobile-label" data-label="">{c.ad || '—'}</td>
                        <td className="customers-td-grubu" data-label="Müşteri Grubu">{getMusteriGrubuText(c.musteri_grubu || '')}</td>
                        <td data-label="Kupon Kodu">
                          <span className="campaigns-kupon-badge">{c.kupon_kodu || '—'}</span>
                        </td>
                        <td data-label="Başlangıç">{c.baslangic_tarihi ? new Date(c.baslangic_tarihi).toLocaleDateString('tr-TR') : '—'}</td>
                        <td data-label="Bitiş">{c.bitis_tarihi ? new Date(c.bitis_tarihi).toLocaleDateString('tr-TR') : '—'}</td>
                        <td data-label="Durum">
                          <span className={`status-badge status-${c.durum || 'taslak'}`}>
                            {getStatusText(c.durum || '')}
                          </span>
                        </td>
                        <td className="campaigns-td-islemler" data-label="İşlemler">
                          {c.durum === 'tamamlandi' ? (
                            <span className="campaigns-tamamlandi-mesaj">
                              Tamamlanan kampanyalar ile ilgili işlem yapılamaz
                            </span>
                          ) : (
                            <div className="flex items-center justify-center">
                              <div className="islem-ikonlar">
                                <button
                                  type="button"
                                  className="islem-ikon duzenle-ikon"
                                  data-tooltip="Düzenle"
                                  onClick={(e) => {
                                    e.stopPropagation();
                                    handleEdit(c);
                                  }}
                                >
                                  <Pencil size={16} aria-hidden />
                                </button>
                                <button
                                  type="button"
                                  className="islem-ikon sil-ikon"
                                  data-tooltip="Sil"
                                  onClick={(e) => {
                                    e.stopPropagation();
                                    handleDelete(c);
                                  }}
                                >
                                  <Trash2 size={16} aria-hidden />
                                </button>
                              </div>
                            </div>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Sağ panel - Masaüstünde yan panel, mobilde body'de portal ile tam modal */}
      {isMobile && (showForm || selectedCampaign) &&
        createPortal(
          <>
            <div
              className="page-detail-modal-backdrop campaigns-mobile-modal-backdrop"
              onClick={() => {
                setShowNewForm(false);
                setSelectedCampaignId(null);
              }}
              aria-hidden
            />
            <div
              className="page-panel-sag page-panel-sag--as-modal campaigns-mobile-modal w-full"
              onClick={(e) => e.stopPropagation()}
              role="dialog"
              aria-modal="true"
              aria-labelledby="kampanya-modal-title"
            >
          <div className="page-panel-sag-inner">
          <div className="page-detail-header mb-4 flex items-center justify-between flex-shrink-0">
              <h2 id="kampanya-modal-title" className="page-detail-title">{showForm ? formTitle : 'Kampanya Detayları'}</h2>
                {(selectedCampaignId || showForm) && (
                  <button
                    type="button"
                    onClick={() => {
                      setShowNewForm(false);
                      setSelectedCampaignId(null);
                    }}
                    className="customers-close-detail btn-close-modal md:hidden"
                    aria-label="Kapat"
                  >
                    <i className="icon-btn-kapat" aria-hidden />
                  </button>
                )}
              </div>

              {!showForm && !selectedCampaign ? (
            <div className="page-empty-detail">
              <div className="page-empty-detail-inner">
                <i className="icon-sm-i-kampanyalar mx-auto mb-3 block" id="ikon" />
                <p className="page-empty-detail-text">
                  Yeni kampanya oluşturmak için butona tıklayın veya listeden bir kampanya seçin.
                </p>
              </div>
            </div>
          ) : showForm ? (
            <div className="customers-detail-card campaigns-form-card campaigns-form-wrap" data-card-item>
              <form onSubmit={handleSubmit} className="campaigns-form">
                <div className="campaigns-form-scroll custom-scrollbar space-y-6">
                <div className="campaigns-form-gorsel">
                  <label className="block text-sm font-medium mb-2">Kampanya Görseli</label>
                  <div className="upload-area kampanya-upload-area">
                    {formData.gorsel || formData.gorsel_path ? (
                      <div className="uploaded-preview">
                        <img
                          src={
                            formData.gorsel
                              ? URL.createObjectURL(formData.gorsel)
                              : getUploadUrl(formData.gorsel_path || '')
                          }
                          alt="Kampanya"
                          className="max-h-48 rounded"
                        />
                        <button
                          type="button"
                          onClick={() => setFormData((p) => ({ ...p, gorsel: null, gorsel_path: null }))}
                          className="remove-button"
                        >
                          Kaldır
                        </button>
                      </div>
                    ) : (
                      <div className="upload-placeholder">
                        <input
                          type="file"
                          accept="image/*"
                          className="hidden"
                          id="kampanya-gorsel"
                          disabled={uploadingImage}
                          onChange={(e) => {
                            const f = e.target.files?.[0];
                            if (f) handleImageUpload(f);
                          }}
                        />
                        <label htmlFor="kampanya-gorsel" className="cursor-pointer">
                          {uploadingImage ? 'Yükleniyor...' : 'Görsel sürükleyin veya tıklayın (max 5MB)'}
                        </label>
                      </div>
                    )}
                  </div>
                </div>

                <div>
                  <label>Kampanya Adı *</label>
                  <input
                    type="text"
                    value={formData.ad}
                    onChange={(e) => setFormData((p) => ({ ...p, ad: e.target.value }))}
                    onBlur={() => setTimeout(handleAutoMessage, 0)}
                    placeholder="Kampanya adını yazınız"
                    required
                  />
                </div>

                <div className="form-row-2">
                  <div>
                    <label>Kupon Tanımla *</label>
                    <input
                      type="text"
                      value={formData.kupon_kodu}
                      onChange={(e) => setFormData((p) => ({ ...p, kupon_kodu: e.target.value.toUpperCase() }))}
                      onBlur={() => setTimeout(handleAutoMessage, 0)}
                      placeholder="SEVGILI14"
                      required
                    />
                  </div>
                  <div>
                    <label>Müşteri Grubu *</label>
                    <select
                      value={formData.musteri_grubu}
                      onChange={(e) => setFormData((p) => ({ ...p, musteri_grubu: e.target.value }))}
                      required
                    >
                      {musteriGruplari.map((g) => (
                        <option key={g} value={g}>
                          {getMusteriGrubuText(g)}
                        </option>
                      ))}
                    </select>
                  </div>
                </div>

                <div className="form-row-2">
                  <div>
                    <label>Başlangıç Tarihi *</label>
                    <input
                      type="date"
                      value={formData.baslangic_tarihi}
                      onChange={(e) => {
                        setFormData((p) => ({ ...p, baslangic_tarihi: e.target.value }));
                        setTimeout(handleAutoMessage, 0);
                      }}
                      required
                    />
                  </div>
                  <div>
                    <label>Bitiş Tarihi *</label>
                    <input
                      type="date"
                      value={formData.bitis_tarihi}
                      onChange={(e) => {
                        setFormData((p) => ({ ...p, bitis_tarihi: e.target.value }));
                        setTimeout(handleAutoMessage, 0);
                      }}
                      min={formData.baslangic_tarihi}
                      required
                    />
                  </div>
                </div>

                <div>
                  <label>Kampanya Mesajı *</label>
                  <textarea
                    value={formData.mesaj}
                    onChange={(e) => setFormData((p) => ({ ...p, mesaj: e.target.value }))}
                    rows={6}
                    placeholder="Yukarıdaki ilgili bilgileri tamamladıktan sonra kampanya mesajı otomatik oluşacaktır, oluşan kampanya metnini buradan tekrar düzenleyebilirsiniz."
                    required
                  />
                </div>
                </div>
                <div className="campaigns-form-footer form-actions butonlar">
                  <button
                    type="button"
                    onClick={() => {
                      setFormData(defaultFormData);
                      setShowNewForm(false);
                      setSelectedCampaignId(null);
                    }}
                    className="secondary-button btn-vazgec"
                  >
                    VAZGEÇ
                  </button>
                  <button
                    type="submit"
                    className={selectedCampaign && !showNewForm ? 'primary-button btn-guncelle' : 'primary-button btn-kaydet'}
                  >
                    {submitLabel}
                  </button>
                </div>
              </form>
            </div>
          ) : selectedCampaign ? (
            <div className="page-detail-card campaigns-detail-card" data-card-item>
              <div className="page-detail-card-top custom-scrollbar">
                {(selectedCampaign.gorsel_path || selectedCampaign.gorsel) ? (
                  <div
                    className="kampanya-gorsel-preview mb-4 cursor-pointer"
                    role="button"
                    tabIndex={0}
                    onClick={() => setCampaignImageLightboxOpen(true)}
                    onKeyDown={(e) => e.key === 'Enter' && setCampaignImageLightboxOpen(true)}
                    title="Görseli büyüt"
                  >
                    <img
                      key={selectedCampaign.id}
                      src={`${getUploadUrl(selectedCampaign.gorsel_path || selectedCampaign.gorsel)}?t=${selectedCampaign.id}`}
                      alt={selectedCampaign.ad}
                      className="max-w-full max-h-48 rounded"
                    />
                  </div>
                ) : null}
                <div className="page-detail-block page-detail-block-sep">
                  <p className="page-detail-label">Kampanya Adı</p>
                  <p className="page-detail-value">{selectedCampaign.ad}</p>
                </div>
                <div className="page-detail-block page-detail-block-sep">
                  <p className="page-detail-label">Müşteri Grubu</p>
                  <p className="page-detail-value">{getMusteriGrubuText(selectedCampaign.musteri_grubu || '')}</p>
                </div>
                <div className="page-detail-block page-detail-block-sep">
                  <p className="page-detail-label">Kupon Kodu</p>
                  <p className="page-detail-value"><code>{selectedCampaign.kupon_kodu || '—'}</code></p>
                </div>
                <div className="page-detail-block page-detail-block-sep">
                  <p className="page-detail-label">Tarihler</p>
                  <p className="page-detail-value">
                    {selectedCampaign.baslangic_tarihi && new Date(selectedCampaign.baslangic_tarihi).toLocaleDateString('tr-TR')} –{' '}
                    {selectedCampaign.bitis_tarihi && new Date(selectedCampaign.bitis_tarihi).toLocaleDateString('tr-TR')}
                  </p>
                </div>
                <div className="page-detail-block page-detail-block-sep">
                  <p className="page-detail-label">Durum</p>
                  <span className={`status-badge status-${selectedCampaign.durum || 'taslak'}`}>
                    {getStatusText(selectedCampaign.durum || '')}
                  </span>
                </div>
                {selectedCampaign.mesaj && (
                  <div className="page-detail-block page-detail-block-sep">
                    <p className="page-detail-label">Kampanya Mesajı</p>
                    <p className="page-detail-value mesaj-text">{selectedCampaign.mesaj}</p>
                  </div>
                )}
                {!selectedCampaign.gonderildi && (
                  <div className="mt-4">
                    <button
                      type="button"
                      onClick={() => handleEdit(selectedCampaign)}
                      className="page-detail-btn-edit"
                    >
                      <Pencil size={16} />
                      <span>Kampanyayı Düzenle</span>
                    </button>
                  </div>
                )}
              </div>
            </div>
          ) : null}
              </div>
            </div>
          </>,
          document.body
        )}
      {/* Web: sağ panel her zaman görünsün (Müşteriler/Partner ile aynı); boşken empty state */}
      {!isMobile && (
        <div
          className="page-panel-sag w-full md:w-1/2 lg:w-3/5"
          onClick={(e) => e.stopPropagation()}
        >
          <div className="page-panel-sag-inner">
            <div className="customers-detail-header mb-4 flex items-center justify-between flex-shrink-0">
              <h2 id="kampanya-modal-title" className="customers-detail-title">{showForm ? formTitle : 'Kampanya Detayları'}</h2>
            </div>
            {!showForm && !selectedCampaign ? (
              <div className="page-empty-detail">
                <div className="page-empty-detail-inner">
                  <i className="icon-sm-i-kampanyalar mx-auto mb-3 block" id="ikon" />
                  <p className="page-empty-detail-text">Yeni kampanya oluşturmak için butona tıklayın veya listeden bir kampanya seçin.</p>
                </div>
              </div>
            ) : showForm ? (
              <div className="page-detail-card customers-detail-card campaigns-form-card campaigns-form-wrap" data-card-item>
                <form onSubmit={handleSubmit} className="campaigns-form">
                  <div className="campaigns-form-scroll custom-scrollbar space-y-6">
                    <div className="campaigns-form-gorsel">
                      <label className="block text-sm font-medium mb-2">Kampanya Görseli</label>
                      <div className="upload-area kampanya-upload-area">
                        {formData.gorsel || formData.gorsel_path ? (
                          <div className="uploaded-preview">
                            <img src={formData.gorsel ? URL.createObjectURL(formData.gorsel) : getUploadUrl(formData.gorsel_path || '')} alt="Kampanya" className="max-h-48 rounded" />
                            <button type="button" onClick={() => setFormData((p) => ({ ...p, gorsel: null, gorsel_path: null }))} className="remove-button">Kaldır</button>
                          </div>
                        ) : (
                          <div className="upload-placeholder">
                            <input type="file" accept="image/*" className="hidden" id="kampanya-gorsel-desktop" disabled={uploadingImage} onChange={(e) => { const f = e.target.files?.[0]; if (f) handleImageUpload(f); }} />
                            <label htmlFor="kampanya-gorsel-desktop" className="cursor-pointer">{uploadingImage ? 'Yükleniyor...' : 'Görsel sürükleyin veya tıklayın (max 5MB)'}</label>
                          </div>
                        )}
                      </div>
                    </div>
                    <div><label>Kampanya Adı *</label><input type="text" value={formData.ad} onChange={(e) => setFormData((p) => ({ ...p, ad: e.target.value }))} onBlur={() => setTimeout(handleAutoMessage, 0)} placeholder="Kampanya adını yazınız" required /></div>
                    <div className="form-row-2">
                      <div><label>Kupon Tanımla *</label><input type="text" value={formData.kupon_kodu} onChange={(e) => setFormData((p) => ({ ...p, kupon_kodu: e.target.value.toUpperCase() }))} onBlur={() => setTimeout(handleAutoMessage, 0)} placeholder="SEVGILI14" required /></div>
                      <div><label>Müşteri Grubu *</label><select value={formData.musteri_grubu} onChange={(e) => setFormData((p) => ({ ...p, musteri_grubu: e.target.value }))} required>{musteriGruplari.map((g) => <option key={g} value={g}>{getMusteriGrubuText(g)}</option>)}</select></div>
                    </div>
                    <div className="form-row-2">
                      <div><label>Başlangıç Tarihi *</label><input type="date" value={formData.baslangic_tarihi} onChange={(e) => { setFormData((p) => ({ ...p, baslangic_tarihi: e.target.value })); setTimeout(handleAutoMessage, 0); }} required /></div>
                      <div><label>Bitiş Tarihi *</label><input type="date" value={formData.bitis_tarihi} onChange={(e) => { setFormData((p) => ({ ...p, bitis_tarihi: e.target.value })); setTimeout(handleAutoMessage, 0); }} min={formData.baslangic_tarihi} required /></div>
                    </div>
                    <div><label>Kampanya Mesajı *</label><textarea value={formData.mesaj} onChange={(e) => setFormData((p) => ({ ...p, mesaj: e.target.value }))} rows={6} placeholder="Kampanya mesajı..." required /></div>
                  </div>
                  <div className="campaigns-form-footer form-actions butonlar">
                    <button type="button" onClick={() => { setFormData(defaultFormData); setShowNewForm(false); setSelectedCampaignId(null); }} className="secondary-button btn-vazgec">VAZGEÇ</button>
                    <button type="submit" className={selectedCampaign && !showNewForm ? 'primary-button btn-guncelle' : 'primary-button btn-kaydet'}>{submitLabel}</button>
                  </div>
                </form>
              </div>
            ) : selectedCampaign ? (
              <div className="page-detail-card customers-detail-card campaigns-detail-card" data-card-item>
                <div className="page-detail-card-top customers-detail-card-top custom-scrollbar">
                  {(selectedCampaign.gorsel_path || selectedCampaign.gorsel) && (
                    <div
                      className="kampanya-gorsel-preview mb-4 cursor-pointer"
                      role="button"
                      tabIndex={0}
                      onClick={() => setCampaignImageLightboxOpen(true)}
                      onKeyDown={(e) => e.key === 'Enter' && setCampaignImageLightboxOpen(true)}
                      title="Görseli büyüt"
                    >
                      <img src={`${getUploadUrl(selectedCampaign.gorsel_path || selectedCampaign.gorsel)}?t=${selectedCampaign.id}`} alt={selectedCampaign.ad} className="max-w-full max-h-48 rounded" />
                    </div>
                  )}
                  <div className="customers-detail-block customers-detail-block-sep"><p className="customers-detail-label">Kampanya Adı</p><p className="customers-detail-value">{selectedCampaign.ad}</p></div>
                  <div className="customers-detail-block customers-detail-block-sep"><p className="customers-detail-label">Müşteri Grubu</p><p className="customers-detail-value">{getMusteriGrubuText(selectedCampaign.musteri_grubu || '')}</p></div>
                  <div className="customers-detail-block customers-detail-block-sep"><p className="customers-detail-label">Kupon Kodu</p><p className="customers-detail-value"><code>{selectedCampaign.kupon_kodu || '—'}</code></p></div>
                  <div className="customers-detail-block customers-detail-block-sep"><p className="customers-detail-label">Tarih Aralığı</p><p className="customers-detail-value">{selectedCampaign.baslangic_tarihi && new Date(selectedCampaign.baslangic_tarihi).toLocaleDateString('tr-TR')} – {selectedCampaign.bitis_tarihi && new Date(selectedCampaign.bitis_tarihi).toLocaleDateString('tr-TR')}</p></div>
                  <div className="customers-detail-block"><p className="customers-detail-label">Durum</p><span className={`status-badge status-${selectedCampaign.durum || 'taslak'}`}>{getStatusText(selectedCampaign.durum || '')}</span></div>
                  {selectedCampaign.mesaj && <div className="customers-detail-block"><p className="customers-detail-label">Mesaj</p><p className="customers-detail-value mesaj-text">{selectedCampaign.mesaj}</p></div>}
                  {!selectedCampaign.gonderildi && (
                    <div className="mt-4">
                      <button type="button" onClick={() => handleEdit(selectedCampaign)} className="customers-btn-duzenle"><Pencil size={16} /><span>Kampanyayı Düzenle</span></button>
                    </div>
                  )}
                </div>
              </div>
            ) : null}
          </div>
        </div>
      )}

      {exportMenuOpen && (
        <div className="fixed inset-0 z-10" onClick={() => setExportMenuOpen(false)} aria-hidden />
      )}

      {selectedCampaign && (selectedCampaign.gorsel_path || selectedCampaign.gorsel) && (
        <Lightbox
          isOpen={campaignImageLightboxOpen}
          images={[{ src: `${getUploadUrl(selectedCampaign.gorsel_path || selectedCampaign.gorsel)}?t=${selectedCampaign.id}`, alt: selectedCampaign.ad }]}
          onClose={() => setCampaignImageLightboxOpen(false)}
          enableZoom
        />
      )}
    </div>
  );
};
